"""
SENTINEL — Refresh Token Repository
"""

import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional

from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.security import hash_refresh_token
from app.models.refresh_token import RefreshToken
from app.repositories.base import BaseRepository


class TokenRepository(BaseRepository[RefreshToken]):
    """Data access layer for refresh token management."""

    def __init__(self, db: AsyncSession) -> None:
        super().__init__(RefreshToken, db)

    async def create(self, user_id: uuid.UUID, raw_token: str) -> RefreshToken:
        """
        Persist a new refresh token (storing only the hash).

        Args:
            user_id: The owning user's UUID.
            raw_token: The plain-text token generated by generate_refresh_token().

        Returns:
            The newly created RefreshToken record.
        """
        expires_at = datetime.now(timezone.utc) + timedelta(
            days=settings.REFRESH_TOKEN_EXPIRE_DAYS
        )
        token = RefreshToken(
            user_id=user_id,
            token_hash=hash_refresh_token(raw_token),
            expires_at=expires_at,
        )
        return await self.save(token)

    async def get_by_raw_token(self, raw_token: str) -> Optional[RefreshToken]:
        """
        Look up a refresh token by its plain-text value.

        Hashes the raw token before querying — the database never sees
        the raw token.
        """
        token_hash = hash_refresh_token(raw_token)
        result = await self._db.execute(
            select(RefreshToken).where(RefreshToken.token_hash == token_hash)
        )
        return result.scalar_one_or_none()

    async def revoke(self, token: RefreshToken) -> None:
        """Mark a refresh token as revoked (soft delete)."""
        token.revoked_at = datetime.now(timezone.utc)
        await self._db.flush()

    async def delete_for_user(self, user_id: uuid.UUID) -> None:
        """
        Delete ALL refresh tokens for a user.

        Used for "logout from all devices" functionality.
        """
        await self._db.execute(
            delete(RefreshToken).where(RefreshToken.user_id == user_id)
        )
        await self._db.flush()

    async def purge_expired(self) -> int:
        """
        Delete expired, non-revoked tokens.

        Should be called periodically (e.g., via a scheduled task or
        a maintenance endpoint) to keep the table clean.

        Returns:
            The number of records deleted.
        """
        now = datetime.now(timezone.utc)
        result = await self._db.execute(
            delete(RefreshToken).where(
                RefreshToken.expires_at < now,
                RefreshToken.revoked_at.is_(None),
            )
        )
        await self._db.flush()
        return result.rowcount
