"""Initial migration

Revision ID: c82335ba9c5a
Revises: 
Create Date: 2026-07-09 07:43:43.523941+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c82335ba9c5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False, comment="Semantic version string, e.g. '1.0.0'"),
    sa.Column('algorithm', sa.String(length=100), nullable=False, comment='Human-readable algorithm name'),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('precision_spam', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('recall_spam', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('f1_spam', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('model_file_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False, comment='RFC 5321 max email length is 320 chars'),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False, comment='bcrypt hash, always 60 chars'),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False, comment="'LOGIN' | 'LOGOUT' | 'REGISTER' | 'PREDICT' | 'DELETE_PREDICTION' | ..."),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='Client IP (INET type for both IPv4 and IPv6)'),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False, comment="'SUCCESS' | 'FAILURE'"),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional context (error message, changed fields, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('processed_text', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=False, comment="'sms' | 'email' | 'text'"),
    sa.Column('verdict', sa.String(length=4), nullable=False, comment="'SPAM' | 'HAM'"),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, comment='0.0000 to 1.0000'),
    sa.Column('risk_level', sa.String(length=6), nullable=False, comment="'LOW' | 'MEDIUM' | 'HIGH'"),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('suspicious_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='[{token: str, weight: float}, ...]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the raw refresh token UUID'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Set when the token is invalidated (logout or rotation)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
